- name: Check route presence
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: route-example
    name: route-one
  register: route
  until: route.resources | length > 0
  retries: 10
  delay: 3
