- hosts: localhost
  vars:
    state: present
    with_backup: false
    with_restore: false
  roles:
    - deployment/replica_set
    - scc
    - net-policy/net-policy-extended
    - rbac/basic_sa_with_role
    - quotas_limits/resource_quotas
    - pvc/mysql_pvc
    - deployment/nginx_deployment
    - route/route_example
    - s2i/cakephp_backup_restore
    - service/basic-service
    - basic_app_examples/nginx_backup_restore
    - imagestream/mysql_centos7
    - crd/simple_crd
    - pod/hello-pod
    - pipeline/pipeline_example
