- hosts: localhost
  vars:
    travisCI: "{{ lookup('ENV', 'TRAVIS') }}"
  vars_prompt:
    - name: user
      prompt: "Cluster login"
      private: no
  roles:
  - login_ocp
  - imagestream/mysql_centos7
