# This role assumes that you use the multitenant plugin for networking
- hosts: localhost
  vars:
    state: present
    with_backup: true
    with_restore: true
    prompt_login: "{{ lookup('ENV', 'PROMPT_LOGIN') }}"
  roles:
  - login_ocp
  - net-policy/net-policy-ext-multitenant
