- hosts: localhost
  vars:
    travisCI: "{{ lookup('ENV', 'TRAVIS') }}"
    state: present
  vars_prompt:
    - name: user
      prompt: "Cluster login"
      private: no
  roles:
  - login_ocp
  - net-policy/net-policy-extended
  - net-policy/net-policy-ext-multitenant
