- name: Create ark backup of resources
  k8s:
    state : present
    definition: 
      apiVersion: ark.heptio.com/v1
      kind: Backup
      metadata:
        name: "{{ backup_name }}"
        namespace: heptio-ark
      spec:
        labelSelector:
          matchLabels:
            app: "{{ backup_label }}"
        storageLocation: default
        ttl: 720h0m0s
        includedNamespaces:
        - '*'

- name: Wait for backup to complete
  k8s_facts:
    kind: Backup
    api_version: ark.heptio.com/v1
    namespace: heptio-ark
    name: "{{ backup_name }}"
  register: backup
  until:  backup.get("resources", []) | length > 0
          and backup.resources[0].get("status", {}).get("phase", "Completed")
          == "Completed"
  retries: 20
  delay: 30
