- name: Deploy cakephp
  block:
    - name: Deploy cakephp from yml
      k8s:
        state : present
        definition: "{{ lookup('file', 'cakephp-template.yml')}}"

    - name: Wait for cakephp deployment
      k8s_facts:
        kind: Pod
        namespace: cakephp-example
        label_selectors: "app=cakephp-example"
      register: pod
      until:  pod.get("resources", []) | length > 0
              and pod.resources[0].get("status", {}).get("phase", "") == "Running"
      retries: 20
      delay: 30
  when: with_resources

- name: Create backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    # Check every restored resource
    - name: Wait for cakephp deployment
      k8s_facts:
        kind: Pod
        namespace: cakephp-example
        label_selectors: "app=cakephp-example"
      register: pod
      until:  pod.get("resources", []) | length > 0
              and pod.resources[0].get("status", {}).get("phase", "") == "Running"
      retries: 20
      delay: 30
      ignore_errors: yes

    - name: Check for restored secrets
      k8s_facts:
        kind: Secret
        namespace: cakephp-example
        name: cakephp-example
      register: secrets
      until:  secrets.get("resources", []) | length > 0
      retries: 20
      delay: 30

    - name: Check for restored service
      k8s_facts:
        kind: Service
        namespace: cakephp-example
        name: cakephp-example
      register: service
      until:  service.get("resources", []) | length > 0
              and service.resources[0].get("status", {}).get("phase", "") == ""
      retries: 20
      delay: 30

    - name: Check for restored route
      k8s_facts:
        kind: Route
        namespace: cakephp-example
        name: cakephp-example
      register: route
      until: route.get("resources", []) | length > 0
      retries: 20
      delay: 30

    - name: Check for restored build config
      k8s_facts:
        kind: BuildConfig
        namespace: cakephp-example
        name: cakephp-example
      register: bc
      until: bc.get("resources", []) | length > 0
      retries: 20
      delay: 30

    - name: Check for restored deployment config
      k8s_facts:
        kind: DeploymentConfig
        namespace: cakephp-example
        name: cakephp-example
      register: dc
      until: dc.get("resouces", []) | length > 0
      retries: 20
      delay: 30
