- name: Wait 2 minutes for service account to appear
  k8s_facts:
    api_version: v1
    kind: ServiceAccount
    namespace: basic-sa-role
    name: basic-sa
  register: service_account
  until: service_account and (service_account.resources | length > 0)
  retries: 10
  delay: 10

- name: Wait 2 minutes for role to appear
  k8s_facts:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: Role
    namespace: basic-sa-role
    name: basic-role
  register: role
  until: role and (role.resources | length > 0)
  retries: 10
  delay: 10

- name: Wait 2 minutes for role binding to appear
  k8s_facts:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    namespace: basic-sa-role
    name: basic-role-binding
  register: role_binding
  until: role_binding and (role_binding.resources | length > 0)
  retries: 10
  delay: 10
