- name: Checking the build is created and started
  k8s_facts:
    api_version: v1
    kind: BuildConfig
    namespace: pipeline-example
    label_selectors:
      - app = pipeline
  register: buildconfig
  until: buildconfig
          and (buildconfig.resources | length > 0)
  retries: 10
  delay: 5
