---
- name: Create Pipeline
  block:
    - name: Create Jenkins-pipeline BuildConfig
      k8s:
        state: present
        definition: "{{ lookup('file', 'install-pipeline-example.yml')}}"

    - name: Check resource presence
      include: check.yml

- name: Create a backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup

- name: Restore pipeline
  when: with_restore
  block:
    - name: Start restoring
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
