- name: Wait for CRD creation
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: crexamples.samplecontroller.k8s.io
    namespace: crd-example
  register: crd
  until:  crd.get("resources", [])
  retries: 10
  delay: 5
